services:
  pocketbase:
    build:
      context: .
    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb_hooks:/pb/pb_hooks
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - minio
      - mailcrab
    networks:
      - pb_network

  minio:
    image: minio/minio
    volumes:
      - ./minio_data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DOMAIN: myminioserver
    command: server /data --address 0.0.0.0:9000
    networks:
      - pb_network

  mailcrab:
    image: marlonb/mailcrab:latest
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - pb_network

networks:
  pb_network:
    driver: bridge